services:
  redis-primary:
    image: redis/redis-stack:latest
    container_name: redis-primary
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-primary-data:/data

  redis-replica:
    image: redis/redis-stack:latest
    container_name: redis-replica
    command: [ "redis-server", "--appendonly", "yes", "--replicaof", "redis-primary", "6379" ]
    depends_on:
      - redis-primary
    ports:
      - "6380:6379"
    volumes:
      - redis-replica-data:/data

  redis-sentinel:
    image: redis:7.0.12
    container_name: redis-sentinel
    command: [ "redis-sentinel", "/etc/sentinel.conf" ]
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
    depends_on:
      - redis-primary
      - redis-replica

  modnetv2:
    build:
      context: ../docker/modnetv2
      dockerfile: ../docker/modnetv2/Dockerfile
    container_name: modnetv2
    ports:
      - "8080:8080"
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modnetv2
      MYSQL_USER: modnetv2
      MYSQL_PASSWORD: modnetv2
    ports:
      - "3306:3306"

  api-gateway:
    build:
      context: ../docker/api-gateway
      dockerfile: ../docker/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - modnetv2
      - redis-sentinel

volumes:
  redis-primary-data:
  redis-replica-data:
