services:
  redis-primary:
    image: redis/redis-stack:latest
    container_name: redis-primary
    command: [ "redis-stack-server", "--appendonly", "yes", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-primary-data:/data

  redis-replica:
    image: redis/redis-stack:latest
    container_name: redis-replica
    command: [ "redis-stack-server", "--appendonly", "yes", "--replicaof", "redis-primary", "6379", "--protected-mode", "no" ]
    depends_on:
      - redis-primary
    ports:
      - "6380:6379"
    volumes:
      - redis-replica-data:/data

  redis-sentinel:
    build:
      context: ../docker/sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel
    ports:
      - "26379:26379"
    depends_on:
      - redis-primary
      - redis-replica

  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "6333:6333"

  # mpnetv2:
  #   build:
  #     context: ../docker/models/mpnetv2
  #     dockerfile: Dockerfile
  #   container_name: model
  #   volumes:
  #     - ../docker/models/weights/mpnetv2/mpnet-base-v2:/app/mpnet-base-v2
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - LOCAL=1

  snowflake-arctic:
    build:
      context: ../docker/models/snowflake-arctic
      dockerfile: Dockerfile
    container_name: snowflake-arctic
    # volumes:
    #   - ../docker/models/snowflake-arctic/weights:/app/snowflake-arctic
    ports:
      - "8000:8000"
    environment:
      - LOCAL=1

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thinkpixel
      MYSQL_USER: thinkpixel
      MYSQL_PASSWORD: thinkpixel
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # Monitoring endpoint

  api-gateway:
    build:
      context: ../docker/api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - LOCAL=1
      - API_GATEWAY_ENABLE_INSECURE_VALIDATION=1
      - API_GATEWAY_VALIDATION_MAX_ATTEMPTS=10
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - qdrant
      - nats
      - snowflake-arctic

  mock-site:
    build:
      context: ./mock_site
      dockerfile: Dockerfile
    container_name: mock-site
    networks:
      default:
        aliases:
          - example.com
    ports:
      - "8081:80"

volumes:
  redis-primary-data:
  redis-replica-data:
  mysql-data:
  qdrant-data:
