---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qdrant-secret
spec:
  encryptedData:
    QDRANT__SERVICE__API_KEY: AgAw9RPAeYNqGuCd8Z9yo283KbJCibaj+T8qBaav7GlLYSR+tVAF76PqTMJMzgOJ4esg9zWRjXGrJm8LYqjfD2zu4zrKrvnhpa5BElFSZkkaDo9QHvVWl5DbLBbwGX88ijh2UUNzDPOOI0/Q/LU+KkxwSO/4p1HeZkwv2WLwLqSn6op97FxQPOk7zQIXbjaKMRKkFXAwKP7Vs3OUad9wMRV7Q8bo2Xjbet3PrPCUgl+ePUFQs9sAS+FyRYYzt/frTVqr5Ld6A0xtpTzKDoFqiQLtx9RzM1ZczfZmkpVcGO4heLHbB9YRuOMCc2JLYLpk7GD9JbVeZ7MTvZw9jnGBUKScZaX4X5ULVX79l8ItRZ1BfoxeJeHmp0ct/cLLrfwxBOYvfKMf2YZyUzP5tvBANxTI/mEjV2kk6gVfXa/GJJfWKowXyDTD45L01msj+IKxGb4xL7TSPF40fkAuwNKIr/4Olc14bAJNLhHaM/0mpi2S28Pijx7gnk8SOq4UIV5ZnOs7i0ioOWdFRdCk4zng6R2YdAzfXgXZa7NvlFK8wjPxFk4SjMgn95SMdiXUmyKpqss2lOOqKMbDJ44cW8thH1aqWT7Q9h8FJ3t5aXsUaV3KixJgrU7Do9G/XjV7nXFEhOBxDtWVJDhijbxbXnWe2G3QX7085I6MJYqAhuWRY26yxC4E721pJhZ1l0f1r3D7ZkggNb19s5jhMTgx9ZBO2Ir+WkY1ygl53WA=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: vectordb
        app.kubernetes.io/name: qdrant
      name: qdrant-secret
      namespace: thinkpixel
    type: Opaque
