---
resources:
  - ../../base/namespace
  - ../../base/secrets
  - ../../base/mysql
  - ../../base/api-gateway
  - ./redis
  - ./models
  - ./qdrant

namespace: thinkpixel

patches:
  - path: patches/api-gateway-sealed-secret.yaml
    target:
      kind: SealedSecret
      name: api-gateway-secret
  - path: patches/fluent-bit-sealed-secret.yaml
    target:
      kind: SealedSecret
      name: fluent-bit-secret
  - path: patches/redis-sealed-secret.yaml
    target:
      kind: SealedSecret
      name: redis-secret
  - path: patches/mysql-sealed-secret.yaml
    target:
      kind: SealedSecret
      name: mysql-secret
  - path: patches/quay-io-sealed-secret.yaml
    target:
      kind: SealedSecret
      name: quay-io-secret
  - path: patches/qdrant-sealed-secret.yaml
    target:
      kind: SealedSecret
      name: qdrant-secret
