---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAeU2NgwXgBXdR5uq008W1/s+clEDTtW5tMNNyLFzx6QLsCTr/V427svla/jjoRyQK8nHkrlVZTWNGJYRngdGeYvvgHcZntHmaHOI6IuWZhd/uUZJ1MHjdOW8GT6f8qnQNkjw0ezhwiz+Q8HEfrOJRmH6JIHuhFrB6mT/FEOINGJ+8sNr+aWdb/ErAMN59yvjPqXJ/m8ydMNa4rVnhS4634WkTghqITE6mvbrb4++k+7M2Awts/XEfpdpsKVbNiyetsb+eohGwkAAPErodU7o/he3E0+qUEm57o5xIB7B1W12jmewRQLOY5Q940SZcVl4IwSCQehBNz9h4EMlo/epvwt4Kd7F5nK93rfkuCpXAE/v+POLIUdHsWrDLdFI0y0zbeoe/T9O9d1orom0v5LqNTLtrjCwcjTPcwaxphrMvb0ftqSFcL2cb2huS1LUFvQdI1NOlF5I10r+aCM7F2QdpxpFSRYBye6fbylcsx6nZ4UJZbrpYZyn8x0P6Dr8Bm2aCU870mk+9qAyusaCQMvrYTSfkKL/zsfLCGswOIBAs8bztOGtapEx4MkkmX2mr60kVHno2Pv1IudsQh/GxPKudz3j/bipSGn9QsKoLelxt2jXOZFgXQhB+ostOdIfAAv4qpE8Y7PULgTTfQOx3MsXNQkV35k5ZhcAKBMmPe2mk/kgU9PskeMA2h6LPPlgtXr12JsKqjkWB85A4rWY9R0HE9vaM4IvUO2U4=
    GF_SECURITY_ADMIN_USER: AgBaavVARd7s5wag8t4meTZ3zIiE6mU+k6Wva3ByVHkqGZmhhboMnribM2K+2thPta3VXs0FYsmwa0ecBgVBOcixUDt4vWQCOK+JJ1yHs2SEdp5WZav7lJn/redP0ibbLyXiAKa9A0ji565nruKGJpV/GF4Lu9PjkEwRZ+bqziLeiUIkFATmvQKEtchHa3EymGMpJN3v+32Yefj2kyaisL1Jqwi0KqI5cupY7pL1QXh/mkLYoZmiEBLcaRctHjQOSWR8PC8WRabRIZvdVB43Cgvc/erVHNIwsQ45jfteT5QKd8fyT7aAQ56lgf/NT3gdCzBNlzpTzQCm6Tl2+RtN2noZJULmR4CbXXWyOZNTHgI+YJPiXFz/2aejfsgjrWNcOSQrX/dWAfJYlW7OtAfEUoSEKq1MctW1ekXPfIpbkQy7ifFMtWT/9qbavIxql2uKFmALO4djyq8UWTwxBpux3aFY1loJWUzGOFd8fjJD3p6qndpYpdY3oLhjlZUnou6U26s1Tqxt1ZNRP7jLD8YefeiIbBsbnK9SwYv91dMzNq8kFiwnP+jUS7QJmbDDsMkY7Og51ytioRwJu6TV9II2uOoCMuYqdv5HwHbLVFFzM+U/6CgVfn94NuoFpWrQalFSG46l8BflPGu3cBQVwqL2fyraCAEijmvr33PZthhBbDxq2pCUqNyrQSEJ3mHhOYC2QQHoq9s7S90xVAaF
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque
