---
# prometheus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/component: monitoring
    spec:
      serviceAccountName: prometheus
      tolerations:
        - key: "dev.thinkpixel.io/taint"
          operator: "Equal"
          value: "monitor"
          effect: "NoSchedule"
      containers:
        - name: prometheus
          image: prom/prometheus:v3.1.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=14d"
            - "--storage.tsdb.retention.size=5GB"
            - "--storage.tsdb.wal-compression"
            - "--storage.tsdb.min-block-duration=2h"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: secrets
              mountPath: /etc/prometheus/secrets
            - name: data-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
        - name: secrets
          secret:
            secretName: prometheus-secret
        - name: data-volume
          persistentVolumeClaim:
            claimName: prometheus-pvc
