---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secret
spec:
  encryptedData:
    qdrant_api_key: <encrypted-qdrant-api-key>
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/name: prometheus
      name: prometheus-secret
    type: Opaque
