---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/version: 0.1.0
data:
  my.cnf: |
    [mysqld]
    sql_mode=STRICT_ALL_TABLES
