---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: <encrypted-root-password>
    MYSQL_PASSWORD: <encrypted-user-password>
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
    type: Opaque
