---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/version: "0.1.0"
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      tolerations:
        - key: "dev.thinkpixel.io/taint"
          operator: "Equal"
          value: "api"
          effect: "NoSchedule"
      containers:
        - name: mysql
          image: percona/percona-server:8.0.40-31.1-multi
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 2Gi
          envFrom:
            - secretRef:
                name: mysql-secret
          env:
            - name: MYSQL_DATABASE
              value: thinkpixel
            - name: MYSQL_USER
              value: thinkpixel
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app.kubernetes.io/name: nysql
          app.kubernetes.io/component: api-gateway
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
