---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-arctic
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snowflake-arctic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snowflake-arctic
    spec:
      containers:
        - name: ml-model
          image: quay.io/bdobrica/thinkpixel-snowflake-arctic-multi:0.1.2
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 1000m
              memory: 3Gi
