---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB0D3RTnkJA22dUBk7Ke2e2nzxWTzoztgwCoxy9TjgjkVmIWXVFL50/4hdBNT5F5mn5ioyd7AqYSpptmT7v/tWO7NR0MciTIk5roRgxdnqAZFXQ4VC4ViB/SSKM6VzZC3AMMseDMyji6fm+m2V3Bz+J2QATgAhbjGrXOgG+6OU7Fwh+LHp74YU86sPYGwEUh5NNWl19qMV+od152Dkld5ovQBCqQO+Wswf8zbl01l6RAY2FcrPNB00lcPwtHtsRztTXvgzSUnT2GnkcaFIPiMw8N6RuYpRBZ9vTIjNq6dI7CVepnl/lezaw6HmK1Rg9hp6eglDF4Oa65v7WXILGC4JUvXfRFuaECNooHBs/GJh/LKRw2QWNMJBAHNcWAnjeJnA0wMPy/aH1j+SnrEbN8MXY1f8J8Fm/YLMS/X7EuJ7clHE+ph98A66ZDn7YzJnS3ZNRuqD4XJrN8quQIEh9OcD414Bzc+tvLy8DHdutTnTggcTBRWi7ghnlHQ9ErwcIALCu8zuOlts3awAz5i95q3voO7Hz5CK5bxVAR8Gi20PmIqZJdeaH5XE3pd4Uv6Yo6xhsoglGcM+X/eTRuGyXeUWWdT/m3oSQUbHPxV+NKN0qolwfu5I/OvLggrSxMYpGAke8AZ22R6Q1/MYHuP1DtCCGscO8CVkqXJh/gJIkSw1fGa4zpMVZqpZEX/omyfeKeHZoAPRmvBlo6IK8qRMkGFIk45hr/lQWS3DcTuR/VU6lTEYuU2DRO9/tXUSdOA==
    admin-user: AgCWL3U54g5v0sdDAujd5ol/v4dGOUnLDIDs0MFQPE6K7QgwWXkkBIJEOrXsICEiUHd1nRvdARyzDtcG6usSFhHspZANBDCtyCC0hOQOh2ovbdutfxFV686wsFWTeL4OArIiZB1XSgJLKt1Z5KSD1/wUti+sVtk2VFY1+YS5seKcdaSjYAwOtaorNt2B5PXbQRXYfHec3fFnvWP/W78VjmCG2poSq+S0FV8DftSulriVQVvUYNS95lFfV0VxQfapX5Ex5q5wjhChpydNQHeerb9bU/SqbCXMS2M53TOu+hlQbtfOk53hK2PkDThqpGlgR5xfe6Spqu9ch2QrS6HJ8utK7lKFbdCv2wkVnmy9uE05Iabt4Ddxyds5emZABNiH1Can6zO8ilFiQaXYkXIjjIrGlQB8YMDeCjPdE5PeUsZI08ozId2y3gc6yW5Mzix4RwHpdgkaU+GL1nr5KrsNh8uy4mfEgTKbRBQKpEXdqu/7mzHJJ8y8W2bXrMBtTom8uAcF3HuBixTdk1QNES1Djzo50DbgqUCtAqha6jld4rUfZr3SbwQkz7/aCpJMux8NvqM+03Q5kxLCsd5oi5hcybwwq12jYxZgMlBuye8d55tkqmKs9ilkH4TASfxnf5ZuFOySHakoDqNDOleUwUSc1bzpj7eonppZTqKTU/Hi1Y9lQvB9Rye6+2di5iSNADEZg4Fik3rQoDIZczSjcddiSHVP
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
    type: Opaque
