---
resources:
  - ../base/helmrelease.yaml
  - ../base/helmrepository.yaml
  - ./grafana-sealed-secret.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: monitoring
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
