---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secret
  namespace: monitoring
spec:
  encryptedData:
    qdrant_api_key: AgAiHlwBpbO13YOyjFR+au7D9S/3DDupp0iuWinqUDGVKf5oDhPvKaFGpe2latRmxov3xkTaDu1ZHzwINyISXaxg3LDMEmOB+tPanTlGL9zPALB06Gpe6Ea6UTeT92Zhzr2XRt+UhZpNvc1X0dMi70U24+dOHJOD88t8Ih8p0k2RtUTr1jR8PceGDgPtat52QFFyR6JsWlFzkxlSUtvGdSuDsteIM2RwcVRqXUZO3eC9czC9KtuwM7cenZ0VrrJ4E6fcD2HdMGnPbirzcX7nAdolSJCEyVie6+fP8LHRQA1rKkPitkOdBBCQ0gvPg5Ay5nW05asjaUvjYGXU+q6/IEMGa1bqfxgioK0T9+zAtvIYkQTMWvJrd3qRraYBJkvvxMd6UEBD66+R4g/OgUHh/kMKfM8DLT8V6tq2lye4jAUct+TWZLzQ66eqIpRVo9nvD1sWfshTvBAPDrEtk2jQ/37vves4pbgLYIx72gfYQTfaA1ilhpb/PsoGi9KnUfwZS2D2wbGqF08idxh9olnITAgTy+Za2rKt0c1yFOVCU8HFkyHNcWMX32adRoNkxJkc0VuWKCJZ2qt8KPKbIZNSUjNWYyMxnjjKngj6ejkP9uPhP5vpauuBARuLNu8tiIXpIzydELbORKFpdzqDTj+sZFkba6E4jmMpZ+hhAgQ4XdZVdD13F9syoBK8GKWAZZigvn4PUmmII0G852dOvMwx1aMYRuka3jirRBE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/name: prometheus
      name: prometheus-secret
      namespace: monitoring
    type: Opaque
