---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-secret
  namespace: monitoring
spec:
  encryptedData:
    qdrant_api_key: AgBZnfC93zI8Na4IuJuIl1NKB6Lu5cyn8vbYVZ4LWAZ3MUV/h2Ts8XxGfdzfPvn1ZB/C3rBsdqoysLc0Sh7ks3rWZB92KK5TmzPOEM1EqY7QHuzZqT9bAizWxS1mGVMoD+BYiNr12X0qt5HvoMz8YelB3OEYECqC/2Qx+fNZW8V2sTy5tYzQ8QSWYCFL08XVJZ/XCkDK1yRGoeEz0r+mmOrkLSoXB6wscOkWLEaROXPVmm1Qc5nYDWDINueY68AxhalUl7YH5QZh6HcRf3VEj5lzJi0FeXbOswAjgZeUCe0SeyV/UtUPTtrPR9/9LJ/BBOsYjOElMGp6hdSNNmhK61ByRDE/QUvKWx17oS+zZ1b6D4pgduqlAU7ED4bhdCAjzKcjIe4CwWLXcgvsKwUjTVjFMZaD27CsKZoCDdP/E6JM9DJ6ZLxXoJ73KNQiwy2CY2+PXP/2LHTSqtUF9DlE75bFe8QrPm3HedEXB+4DkRFETMnS4Yyk5JSkbIloltXXYsp8uhDcbfpDd9/x15f0F2R+2qSw7WzfJL3YZJq4iljZZNIWlz8//wMBourqYBIV8Ob0nJlX7zRszMvShHrq/A4komqqwmLuC13FV/VuTWzr/L2gqK+87iZYjU/eMP0P7MI8xFNWRaORbrXGhemA1tyl4rFFWzcXnTWKsu8OjGOekyodiA9i5fWhqr1NmyuP4xJ+DLnR5k7cH1I8Enf7KQD8JcQwWwNTRGE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/name: prometheus
      name: prometheus-secret
      namespace: monitoring
    type: Opaque
