---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-kube-prometheus-flux
rules:
  # allow creating CRDs (can't reliably restrict by name for create)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create"]

  # restrict mutation of existing CRDs by name
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames:
      - alertmanagers.monitoring.coreos.com
      - alertmanagerconfigs.monitoring.coreos.com
      - prometheuses.monitoring.coreos.com
      - prometheusrules.monitoring.coreos.com
      - servicemonitors.monitoring.coreos.com
      - podmonitors.monitoring.coreos.com
      - probes.monitoring.coreos.com
      - thanosrulers.monitoring.coreos.com
    verbs: ["update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-kube-prometheus-flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-kube-prometheus-flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: monitoring
