grafana:
  enabled: true
  namespaceOverride: monitoring
  admin:
    existingSecret: grafana
    userKey: admin-user
    passwordKey: admin-password
  tolerations:
    - key: "dev.thinkpixel.io/taint"
      operator: "Equal"
      value: "monitor"
      effect: "NoSchedule"
prometheus-node-exporter:
  namespaceOverride: monitoring
prometheus:
  namespaceOverride: monitoring
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    tolerations:
      - key: "dev.thinkpixel.io/taint"
        operator: "Equal"
        value: "monitor"
        effect: "NoSchedule"
prometheusOperator:
  namespaces:
    - monitoring
  tolerations:
    - key: "dev.thinkpixel.io/taint"
      operator: "Equal"
      value: "monitor"
      effect: "NoSchedule"
kubePrometheusNodeAlerting:
  enabled: false
