{
 "title": "ThinkPixel Dev Container Resource Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\"},container)"
    }
   },
   { "name": "rate", "label": "Rate", "query": "1m, 2m, 5m, 10m, 30m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\r\n  rate(container_cpu_usage_seconds_total{container=~\"$container\", container!=\"POD\", namespace=~\"$namespace\"}[5m])\r\n)",
     "legendFormat": "CPU Cores {{pod}}"
    }
   ]
  },
  {
   "title": "Working Set Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\r\n  container_memory_working_set_bytes{container=~\"$container\", container!=\"POD\", namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "WSS {{pod}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\r\n  rate(container_fs_reads_total{container=~\"$container\", container!=\"POD\", namespace=~\"$namespace\"}[$rate])\r\n)",
     "legendFormat": "Read {{pod}}"
    },
    {
     "expr": "sum by (namespace, pod, container) (\r\n  rate(container_fs_writes_total{container=~\"$container\", container!=\"POD\", namespace=~\"$namespace\"}[$rate])\r\n)",
     "legendFormat": "Write {{pod}}"
    }
   ]
  }
 ]
}