---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
  namespace: thinkpixel
spec:
  encryptedData:
    API_GATEWAY_JWT_SECRET: AgCH2FY9rqurKNehMGQjww5ooYikMFiiPCpkH+axhBa9ZKHgcKsDM/DUfRBCdWNXtSlGqaShFuK2C605sjvh9jlM4az8WkjjrDo90g7R2HvinWfTrS0pz1UrDH9nEUCC0Fuw8CbCmIp5B8/a1czuj0CQ3aw2JotiUUMlG2ZqzZ9Sarlks/kAge6GuxaC5qp9y3LJ9RZR4NBtzLe+QIGltouST/0ja2dWAJCcgtGq4YMytzcOKRcm7H3Ea4bG0so2buRVLIKTeA/0FNW0OtEl7ldF/a3mtVUXFMSHzqvtpG0v2i5W5AKG5kGpFAiGFsHXPQYQYxJRFpmq/SXRc52wK/8CkMGX2pmiuJfJI4WKBVnwnMuMjDdpLK2I4c00EDwyz1Y4X4LggIZeNCuM8ISQ9JTMF9/vzLC1LOqP30eNDPvuXVR9leabL5Oe5XB352aKK67sf4LHSvxmbMe8Rk7YJNO0luv7MEGUlldtWy+7NcbXePn7Tbdt6hg++RuG7Xn1OWyk5fMSZV+NXJ0F1T7d5DT+c8U8JVU3hXMBjl4NDGj0TXsNKSt8S1LPuBdEpNztk5Sh9/PynYkTt0W5GLCmWb489JiyTs74CucIir0QfZJianQUi7UhB8cctYo5rEwzAoI2oQ24SULk/dca6x1iLL0091LKbtzuPsqB4IFU7g3gqTzytgrKrSmSpuGb8XYlMvVs8xDaLb/D/x2GMMQ8mzFj0Gp06HqdXUyT9wosI7V/5xpSaKUua1EcJQDsoKP5nqWY4MnSAxws0aU=
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
      namespace: thinkpixel
    type: Opaque
