apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
  namespace: thinkpixel
spec:
  encryptedData:
    API_GATEWAY_JWT_SECRET: AgATSNksyAQ7yqsS1/vqtzvtYpGtNOinMRzTJdbQhni16wOJAmZCYVLY3GwEBo6rfJpgOynwZ71Var8+XoeHrhnbTXkW+nlT1K88FS1PUPLDrohviGG6KellrwZmbJC+yCYhuEvUsgWd18EKpMf2IaGsDxrokV27ITtxY/SVyC/TMCqY1BM8sUonOR00iDauyRd7G2VbD04X4Y7seVUIUsAC44alB6A8IWZumI7IzGq8YbnLKmjnhgYmENHfG5jgkT4HLJQcToeCrmHTfQHU/bW3Ul544w4260x+rUSCmp4qc8OFdULieOm/t8M5QXVhB+V9bTQLZ7uIhdeq9iVYbiJXQPyQwZwiAJrmArEoAbLVa/0bQgkj6vnvmYd/xaKJJKOJCclL+bKCqbELc07ub5oBxIJEG1cGG/E/yg3WU3gPK4J5ucGPOcVv9K28JS/GjIoreGUsA0P+EktPEILiGAgYNCMT1rYLRYNsj/iyDsG/wPEK87Xw8zCoIBbSfZQpS0f5hSo2ui4OUPeBAc1PK2qXIRaHC+OWJW5bXQyfMEv7yVUgba3Fz8aIVbS8qGBWft5keZ2Pk+nI3Fe0qP20ourmk7EhWAjiPf8F5KuVscUF7rHaoV19uugoE+Mzm2dSg6BQZQiYJBzx6qewZYyzCvq1JtODrpEYlsGhZQHZsUY3z3cjzUwraoqNdefmBze0TcF/IZN+cAnxYHO3GtSkC07oYlnIyGDTpqEHFMHiHW4q2rTBC7mwZUX1gDne1BvYCzhRFoCKWayrp5Y=
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
      namespace: thinkpixel
    type: Opaque
