---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
  namespace: thinkpixel
spec:
  encryptedData:
    API_GATEWAY_JWT_SECRET: AgCmhVCSgfeuroN55E+5OQ6aTZ9L2fUqFD5GuGZYRjeYYk/rIRCDWg0J/+n8cFS9hsRqZ1KMLXPEhX/MQAwTEo18+k5QJkY3zlKYaiwNQkXXr3NNIhu8geOhyFmuIc1kwHJABvNhqwFyw4G/VIyg1Mk7NCxWdK1X8KfAku98D0CTwQmnvqHeJeNQtbpgg4Kn0H5CtXgFnhJu5RI6IPORKkyOsdDa9h33LfNxWdSVG827kd4A2TlsKjBINlUJoYn6EUczMD0gTjb+9Tu8kUmSuKvm5dFtKS+lN6Y17ccsdesqAubitzG5ye3n2n3rMBJ0UofIG/yJOaL47NNWVCWrDbXzkz5lH0IsIu1+mRF6b1vERSzvf5LeXiTkovRcccJp2hyJoTeMB60P9hukFK8pcAz5BK5QPqd10j3DD8WyyKoTqf86pgHArTAwRe9xly6EYBhacYH7RHAsf8AY3OJ+r0lpQTgJ7fqLjR+UdHWPdkBfCLD7yonaGTFdab3yU9PZ6wOeyfuJY6fmN0nntCMYHGnml7f/SyiTCiGYqvUeumUc+d7De8b+8CjtJiixIeMjUAKvHxFcJAeQtHyl1Htk8Gz4wudq8npZmk55znXhgGwF5mrfsLPTTL0C8wQXMlRLhsbHM1M8zbVd0aXcxw7Ichn+ZfA1TWiQE9boL6y+UqggRomhYdcjH43DMSrK3/N6ZjuFBihNQgEUMebGplQp7i5Mlaxtn3XopNFq44kY9wYzaw36txYBQT++iFBrc1q2oReOFETi5sS5rgE=
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
      namespace: thinkpixel
    type: Opaque
