---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: thinkpixel
spec:
  encryptedData:
    root-password: AgAaoK4MA1k3pAqB+Ll6ojpSqq4gxUwxoHHZsuaAc5Yw1SubAYWOzTGlccakBMmJqbOZjOfmX76CuB8VpQiEbaN+zZ6uD0O1rGVqZ2hwzFxoLzOxwkM1kJ21Icy1tprz5esRx1/w/hWRFdcAViNYzHHtR1xnD6sWkQxOk6X9cDc1LE+XqGdhwzJ+HuOFKGQNWpRfhXLLJOhnenNDkahXL4x9OUcpC51l5cjEfGeEYJ4H8+eu2InAYxmnSeK5Nu6MB0zniLuSccllNE8RUlFSulD0dxlh3o8TCMIMwPbF3tAsV2m6oo1SgyGQ2+8kAgTeHsNNG7BmW3RDZCN2o9eBbQFMHFtYnLsJ4Zr5a2s7CFCuAC0fWWY+cmJNp6MojvjTqdaiRq7S6p0xMHepqPklaf1Vqw3O633goHZJ2lLPHlVysBL2G2pWiWJi9lIUYD9OLsr07UA6Ud6VTmZ7pBEAs6BI8sZvi6zOeswxa3zct7htrOWC7fl9A65py7SzjStV1xf38d2TUFrMYHHO5QfMJCLkqpp8tRZ4I+86p1jmenY6q7uxZLFxA5ueFl3uv3AJgszniywr013NGt1U35mpnzuQaeI949ZWUh8qQzfpoll9jaMQKd9usIUBmkhXBHPtL5poL30It+iiCT55CL3Lrjg49vzPcOyYsOA5wbeXUpXYQcWXrRC/KBV/mx1OCqqkFYyghPAqGdNU2HA8gwdqDuU2BGbMvkk8NKM=
    user-password: AgBzAO4mQ6wqgmLknoiKu24iQnIkiridlhiXVVXmXH1/11qsA//NuG0oOJr0jpy5S8fwNPqSZ6f/9dwQtKwAuUWqnbdpzQVj3NEpag+5MD9nSPg4fM476ekC623196Fw8s+/e13IjLBlImiFWOzuCusM+Z+iw4SxGnwiKz03ZogNynVNJ1Qg4mdm3Xqqx4tNPzXvaZfpdV1HoweOTniNrCKjjCuj9TT6D//bYT7tKf//lrJeEHtSjSGZwbajYnirwZMSPHwrob1TVEjYL52nY+xRzcn6cnO0YKbgfd3659qZUrCawHQHggekS6g7iMxT1kQNAxPOXnk7+aKRAw+U91ooFHWwCYGe7HEzKmziYaMccyxy5Hq8lAnWgFZ8VCeiTkrrQk+rVcqDpyn61QQoXk68dwZxK5CEgjEkj90Omu3uXv/tmI1wpKlgE7SRqyfHpKnZv4+aMtNYZ5PYq6DBi1dW9mAE4f7cTnMs4jd7H56E6gbUqfGjDuJcHUt36E7kR+jzKWjlt6V9utl0bTp9yuJgDhJtfIeaXDnhvQ0ru8DNpi6vGWxbeR9ZPItPeDRXhFEKWuabaOUCG//C6w/cqQcJNRgD47aErNSuoGUka96TTJH6CkF7GyD8N2wkyFNZbT96/Jg5fssO/K8m54PZk+wR0bUwI1oFIsulZwWQJc/8TprTXZZaCdnaB5XLwZIgHgfx2fGriAPFeGySd5kmjEeOtxtmT2VkOe8=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: thinkpixel
    type: Opaque
