---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: thinkpixel
spec:
  encryptedData:
    MYSQL_PASSWORD: AgCXj+32AI6mhRtmjSE3KLNzbX1R4gdoDQLT9zrzkl4szR4NUWWBOpNMEx21fWWjTs4McpaCRLmhNczo8+4ucDGzZpT1F/GSgmYdExe1kpG0FnaPgKVJuxDdper9XZugzbGFnkpI/NSTu8bYoX21FIEXrqy3ZpX65uDEHnDzwiAEHrgnRneqTmFORJxzcktwmkefEy8AU/7d8Ot1vptcLMzMR7aC7onXjEji0PIseV4YPkZs0+SVHOYglxXcwtSpOyeoU/3KL8lUxvGXO6rXa3oZiPR81HIP0AEArW+ne6Jg9v1izN5gjTV/cDC/VAmMVW90dJnninnS4aR24B885vEkfSdKS8ZJ45Pt/HCewosvXDUSTM5FtZBQsedq/M5T0J1W0Uffxiwa1GmMhomZPr7AqO9hAToxeLpjS2mg8YXupKKJexT6L56wJtiSE1IF5pdxr90bm1D3x1P2LmzqdXxukirCoR2XIdP0pt/zfvbz8+MM6LdgYXfGFEH+IV4l49QrCJHZtGulGd0wN3X1RPqrKIOAWSTvZQlukmvCWemvy7YpwbLjnroJCINbWJavcn89BvUpyeJZSoU3M2xojzwFNd8CtuSuZUCshSkaSonvUcXmKOgEPBFFwx1z+nU0aeKAe10nGIG7O5F/MN7C+4YaiTAjvKDFmtlkgo82DXXYLC7OiDvK4TQMpz+CEOAC9I8HIcJQpSGDuM/TeY33EK4FE0M3G5s/c7w=
    MYSQL_ROOT_PASSWORD: AgCxfqkJwXI6MwwC5qk/iRmO2+LEky/iLY3lPcNqZ84JPpyVh2GGhdtdKIh1Dddlg4YEFQMvAxpJwe1jnIrJpECwPMAujDckJ+2AOVepjNnOkh/l1rshLhHKEoylObDECq9Ka+V4nC+Xv29YHCiNTx67Z+8L3XFUS3JfAyNko70QcQ+7uqVpYbfBJCZIlAlAO96dpYq7ZdncF6WBxepvxTwfpNnHNqRtuuWrFyinIbiDO4LYLfTqZJ9WI1JNo40FFyWALjLhABQ1vLau5el9ehiLsm4Lv220d3ndZlasqonPZYqs7gIYdZ9wMjicF9O2UlYkD0AGuOmRa4HgizOxQhYXCS7LXQYwrOY9xIw7Xa9yTK2EebZDtU5v/lP6ov7iQNh99A2i9BpjWI0a12L84O715T92ycuK5yI3PCwS0M27MgmdwsebVzDQzXk4Cs1HrPWooG6Q5K/w0dTrqdsD7gTespBIM7wjdkepC2zNlFKuaoXUzW/+D0NMctsSROlzxwuFWpb8ov1+cSKmVBLrmYQz/DzSNGusbJay4UBGb7vDxpWAs9ydHBQdFh8sbAWZjNwYAr7NFk6bHd4zGzhHKY2Dbg3R8+PkJgEt2rLrhv66FQJScZmDNIkZZFOXNi4PIBdpYg9g69lTLFRnidI8OiowGh9Zh5haQt2bs33Tkh6VEO2jlRufcNvKLOXLGkVhmWCP7QSrtXxYmGqQF2W/jMsyDVawqE+9M8w=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: thinkpixel
    type: Opaque
