---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: thinkpixel
spec:
  encryptedData:
    root-password: AgAgLGuZR2L698qmCeNajGfakNRcMvi9ox38cJiEKtV9RmDYeZ/j7ePGiGYE3TtRvz+poIWhl7BGe274NWGfZ3FHtOT1qeo0mEaGKqiW7UmPl0UHnQkFsmr6LwtZzQoJq+CEZHR/9on8s+pl/2xE+OQLy2iQSoZs4fjEyUbTZw4K19CvHTvFt1x/lEFuxzLNXzIoshfqCTKO2CtvzrsI4M/6nJ4C8u/rXc7AcAIBBcRmovoeFaVuzN5jvdC4/JIp26zJAvnifzCpZ+ODYfHk1jI5UAXOrsBmevegFKZkkb+E8YZ6AyxpKiEEA3yWoceLw7yG4QkrW3cyq3V5Fqn/JxDdMMX4GXJcc0Qmqz1K62gWJf1FtBOe7vpTMlZjAbR3kmsrIHKam+lHcPmz7p9h0EWQImdokyg1EzRMgy/FY1mpzuYSap9YrcpnwOLeqq+JiSUxLMa7k4I83mRkkDl7YqMmhUJ8OMdZAOKV4X5Zjfki+EPYpg8wESwrQz3D7BVvopwP8dz+hXzbyT0tfUAZbgQT1S5ab8MlYBHzF/yIqPMn5lZaC3IQHRuufaEPgNQQmLTEK+icccgo4W/KF09xfPPNpmEKD6Xu0ZmOV/GBI27d3x403Mk1JvpUqJplvuFYFMRnpPferzkK1Gmgj70/xeJe0qEN+5Gfd5SOlVTHuDcVv1T4TUoa39o/bhtl/wcfOnsT7SkPMYIVE9uSDQpRpna+AxdrEJ3ENyM=
    user-password: AgBdM/hYiULX6LXU4603h2oAmDQ26N6dLaZ42vJJpabHXfydOMheCRbG+j+voNYqZHkARNYCHBa/4DvdgoGgpnaZoT704QaOB5gA3Z0gat0E3zLMu/yx9RbzLUK3pqOwJ4Qbj1VMHUCsmuzXnQG/JYaKQ9r0/zAY85YwsumO7VT+PdSvvUzOm4P3HKJyJBhsCEkWve13NYJl7dHanmhvgEW7MdscB89mMjUeHOZAmZWJ8Ss1+IlnHQ2NzHSDibC5X8ziKFiJzPXSBaN91w0D2MDth+HcnsAX9RdirJX0Q68zoOixteo1hWuETfy1wGGuO2vLn/h9C+zDYiRO2+1137z0HdZ3ULEa50Rcid2XSQ7zBCLX6dGCcXjfhGizhD4WY9PZRDEo9HDNGu7HXNhfCfIQLI3+Nafh/D9fO43OfRDLXl0MuefQy61gc1Tasw1aNHA6t+KddMAW9UC16Tp3gl0g4ufWJyJMg6+KVR43DHgZbp6c41KihSXurE+tfU6mlGhTKEhukWeSktM8y5ir18HDR//HFgZ7oMRvfLYAyMdKnjGU8dZGvk7OxtOyYBIwCtQkdcQZrfOeMeVPsi9zaQPYfsILeKL9xf4giWCE7bn1EZfOzM4TtlNPYwg4EiaMjdeCQbhWenmqVJGMt3YSgchNUrQec7b1yxaq7C3w9qIBQWwO05tKIfGf/9AG0rQU8ITWx27bQt0ulnIE3FIQofM/oJIU83lh7Vc=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: thinkpixel
    type: Opaque
