---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-io-secret
  namespace: thinkpixel
spec:
  encryptedData:
    .dockerconfigjson: AgAyLQLtFTJbD7y83q0Bnr3uXMWhtV0vnopTQpipanQNgxisU/7lD8kYZ0cKezfmHiiqRta6PdoFQwnFI3TD+yDsyt66oJ3a9Pm6T+DIHmmg0/Vv80vm4Au8LPH9ukBqPFTD/mf6U9DoL4WxZCQs2yxCRm6mdFK9CQOhEnd9DYuF9um9Wr+JHO9t5S0E6zpdZpPZH+TUcu8z4oeW3DAAsv6vRfOHvYPCsabhcPEh0+ZujGgEedQbufqjF2lrUoNv72Dh/I390r/ghvNPxE46vEXIkr1v2JX8jMVFzitTXoSQBoOo7h+yzw8NHayvAysHWR/94ag77iSgnvBH9eElKsXTJYUwku/CDEzGEnidyz+0k0Mo0WMCERaDwAA6pfi/cMwNchUAgB8CE7l3OpEr9vcBeXlm9I1/o4fBdrwmhALimLGFw2sTH6dpGrhCvx9mpuQwa66tKubp+WOEp9y+7FFbLMnII/RqXCtp5WxwacDm1nTqLpBN4iRK/3YlWROZNlGSy+UxkRmWFbwlU4LtEQLxsaM77IFApn4GCwM9SBZZFJqUuKxdLOkti7sQ7RK8LwvD2tPcf20zI5Kb1RLFjj/webQ2ttgB7dfCB+b47dqCqZ4bW4mjo6lhFEGYU901x/OI1BLLopIUnG3D+KeMDFJL/5WynQ4vRG4BWxEDjexGkz71SLe6slkeX8I9lGqrCUc5KNzTXjsp67jybXJKRgbIrpt6fE2kZxjqgqsLwqD6/Xz5AMeWrJZ74Otpf26AG2RBK+bwYi2h1KQqI/MsQoFGH+8GeuJtrg/uvU+1eLOcoLQEBA7bkE0JgWeQ7/GjWQ9ThlUVrNtbNf9r/j7cCKLu8NqEhiqLq5dUnVXYWoVHp0E/EuqwEdPN8abLHpcneTEjgw2R2nnI555XvefnMwZZb2IUwdi5hd6SQPMxne0ki+WFuQqu/SmtEpBEUw5IbuKaA+LDIHqiSKuzzWkL3/WzS1MH
  template:
    metadata:
      creationTimestamp: null
      name: quay-io-secret
      namespace: thinkpixel
    type: kubernetes.io/dockerconfigjson
