---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-io-secret
  namespace: thinkpixel
spec:
  encryptedData:
    .dockerconfigjson: AgAeM05ZrwTBH+mO4flZiIrmgtqEOHnfI4RQMjMQa2gX83e8ZHV85gOHSbD8hTWTOToITztP44TfEJhcV2IWl3joEKxQLOLCgviDlV8BueY5RaVxz6Xb5RvUysrB3DJgA9hMEyPZGxwIVAPXCjPX0jfU8yAoAkwJstk8lkxlm8Bsz87e2E3fwVXN8BIobKclWlhx7hjcmxgYknM/YcedDsWkX9Ha4DyXYW6TtdetRtxWqxrOr65cwQVMTI5h3xr25W19QAPwpoxXh1PHtIHQLVbG6f4rmeoyJnQgtgn9eKPPtFlkQMiwl9XD9yYfp2Iz1iKZyML5ENiUR7mxOowKodLZnI5+DCVNIKTbdaSk3Ao87Dn+kKoVyH5+xfPJKztOujQ93JfBiJkV6BJj43HMonUnCr8T7LdazuEe7DLHPfW8x6zaL7nugkka1GeA7I9Q8aMukUjbdpyEHt2//2P4P4qSWNLtFZSfIe7kGVYlZqAvdGMarhc/nb0tRfcqolmGDZl/cw/QqV3edKCs30O6L03tRr7HzUIRgRM6qIyWJpnhDEO49+12aww1FaYR1y/q7p4oGb9eyZeI1oO2vrGej2IJMuFW7JGA1BCp5ZpEyW0+45EcY4da7WKjrVrZv82XwVYCvVrE0mWVNNOddPqwybvZFYj24UQCgKmlhnC+p0w4BYBvmP/SSZ7Bw7ng4VbOtSKtSlnWBieM5bUC1UiZELZTJLyG1sxT8NeFTAASmSirbav9kJL2CU0NFtiCBKzQjVEx5fGge1y5WyWsBrlL6+qrFH0V0MeTC7Ht+k0P0vhANYFrFdHkF0JJI728CcWqK0DPIbNspGzvFA77wUGyclVjQD6CUAwB0VNVscfOFRCXWGp5Y/VzZ/KmVd4rHkb22+oQK+L3jPqnEre8tRnQGk+sywvru13sYVTkSYuDJxIcgDXsagLCRJuXr76jiugg2ki/dLpxppbPqjowUJkgOb7jGwZS
  template:
    metadata:
      creationTimestamp: null
      name: quay-io-secret
      namespace: thinkpixel
    type: kubernetes.io/dockerconfigjson
