---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-io-secret
  namespace: thinkpixel
spec:
  encryptedData:
    .dockerconfigjson: AgCaUfPTjYmtDEyNipKBWTo3RPtQng0M582Hoawax4di+mv5MkaKQE9qh906HDCis5blC/8/6b/yOUaezOQfqehbYRhtKNa0cVdqmmDsWf/MJUOyMydsspEbhmT5YxhwuObiqjHoh7uduiBC5iuNLceonhhSDXL/di+JtyHcpyFFqpzNwp5F36zTFyJ4nyXfEiTnRL4PgXWH5nzrvCdlfXsdGQlSls792CRsEHgJtspL34jwHBnnsSkMnt8XeLtl4Ds/lerJPuc8Qm7atZp4ySF7AtF8fzw2QVydrVtzo1RA5jbQvH3auscTHhOa0crOVMMDsSlnVQnPPuJ5l9TViNKQzfsawhYk3TegLWQv3T4D8Ejwd68TMVu1xixjU22P3gqHrdX3uk+NBacEiXojGf5EE1g87F6w280c3d397ABnlEyJGn2/JDke5S+Hc1hqXVrd2x+kMSvLh/uwbcDG23GGzPH8lPEyA2mYzqyHfG8a5GORHCxJtN758tnO2GNjUdJejWr5p8QuvrBMnUAbuaHYfjF2p6u+g04A+gXhl4FG3gvWErvcfL5NHyo7vivAB4G8JgT4aW0a7JLuLJhf5iPiHHb57WEIAe73fqMq6WV9yUR17BgZIoygYLzQxip69Rw9VLxhsGF18xwu28DVLMGmh28kYaPg6AD36+qSDYDqOaFb9hWI+Gcr6fd3elreY1NzTaSv55SYt2DZIDkvZyvvvByHvz6/ZsYaa+iWbWIDrOz3Zfun8sOmf94wFbyK+TwMR6j+N2pR8Ihpq1oyc7Sv/TVXmcW2DRkWM6yGr10qEqZYwCeoQSQdiMVMm6ZM81yVcpWP6C1eZrq53WEd46uMTBbdrHUzvgYYaEmfGsD+5HHUcLvHMhmGdnRbI/49gddSrGiwKguNAKWsk2dJnTrW+hm/J94WgM5gEvkvwpNMXyQOzD6XZtxau5HyPAAAQipliqhXT/IPhWGqRw==
  template:
    metadata:
      creationTimestamp: null
      name: quay-io-secret
      namespace: thinkpixel
    type: kubernetes.io/dockerconfigjson
