---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: thinkpixel
spec:
  encryptedData:
    redis-password: AgCgqFCpOxrjB0eY9+bboFgcpkNJlzRxQpB5putenRPFcF0bW1yKZl1b0MUEvShDyRExcM8V7RdweUDmkOfO0J7i0dkaxAZg4uS600yFB4ENm4VHyxOZc3lLQYaDGmexlskbYPZeBNtVe7q2ix/RAExuwDCOt2HMw83DwvWKh6xQsT47yrdLCxYBlRI2YkRPFNjSfy5emool/TO9jnNkWBcc+th1VJZ73icRQN6Z/Ah4p42OKCA1iCLUMUs6PweNeEnguI+HDMn5uL8IG7+RBYZfVFiWzFvVSH2begJleJS4I+IBlD59Hc0tNuy45mOJ34CqImUc80Tb2h1ImzJapeF06d4rX7NzcYydFQAKCkk0br7g4LFA99K4hlR44HLfOH1fee+fWS1OgUi/RWR/kWoFVOzBpIdJnENINx8IonFQA+Ve1Xt1naDufo7v9quCaDH3NtWxrGcticKGeMtqPXtiWY5nDPWuicohFSo4x2aS1uzACj936WdsQSie1+BUC3AKZaKWA6y1A6JVGRTfEM9Pp/AUoNYpb+88hhUgjtmk9VFcYGvr0Bw1yNANFJucZ60aUuXA+qcHM+4kVdOHKX1fmXYRxBzwB7IMlq+c+dichHyiljJ5h2Duie/5O42POGBYzsVskTxsmY1kCfGSW8GmsAjkrZP+M/f1nL5yQ4678NxNCkZB6RKSvxT8VbJ77b+Dy4DrqflnNaNidhb8BnU//BOgt7LGOPY=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: thinkpixel
    type: Opaque
