---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: thinkpixel
spec:
  encryptedData:
    REDIS_PASSWORD: AgBlMtyV4FD5hqvqcPunjg029tkXrLbu5VwPzSHwBYiuoyl/kcmASONC079F3eoXMMrDAHg266IqnQBEbR3r93TRnkAuVwpewhD/+RikGoBQQMg1NXuUAoyuCZ7hJ0nYwAvf8LvlKxA9ZSlDR+Z4gXyUnccLUJU4cD78jXGxcqMuQ+mB/LIFIQxdiFc+A8VUDiIuVxW72+rLuvHBUNZMRwpS5IcFhZx2FQZMT6P0lQf1vTShW2DU8OgXZMomyMHvbnVbDVqzWNq7TRo3vqSTESD0lehw1w54dNijAH7tyAsNJVc+fxMkuqso0z7e0x+wsgKZe2ohnvnThkvPEaxslM/W7Bz+jeFjqTerFjpe5lOL3lxi840k9MYtV3awMLxvJsb2Gs5BKXEpxTBCr80ocriK+4W/wTwR0lzdJ/TAHKIAW+kAa9tERcTisIoP1OpR7w5RYGqec4DZxDn1ootXkgw5SgWTag/kTFELqBGijJNUAJ9oGnXvwNJSv0M7if+WP/zX98/YZFxAGJxD+nGS6ueYBHNJJYOFWSaYKuS5d5NQ23p6ULS7cDZvoNbVEPZFEIowuq1XBkkSYgSZUoStpjQlz2idd0AGdR8jfgATZiS+OYhZRVzDAMt/5vo7DqD0X/9chcUh+zvjK/Mps46gtTm6up/95IfLF1RWjU9al0WQzec4PvLbPhQdz3bT6g8xdkLJUxJM824YbIIBwbOR1uC6no5K1yzfpAM=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: thinkpixel
    type: Opaque
