---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: thinkpixel
spec:
  encryptedData:
    redis-password: AgBJ3X7bfxlEIml6mjP13SAswcPXEYMVYRQezaOrlwuX1hl8v8Hhhqh0gWr4GpWxhXZVLxek63LvIV9jmfURa1AJ0IqIFPdi9nxQXSvmP31JLPBEOse0JZNBw57Wunp+fjXCQOneCpmSfZlO0aQM3zfCx4s9y8cqV3oBQ1iLuYLNAqrrSdZ9xPZBdGzQPvKjOhc++Z93Jft+/K2AireobuwbyDMap/vA6k5FVZYwlzaGY/2utX1sm8euz2mTuMJht2iYoUXAAHHuWVFUYvrigjiU/BG8wy6UWvPM5Wq4YO8y+i0XHgoyM869OEhqXQCBG/7Vk1Y4i5ACWD7HpOZVX/J/5rnkK8rJsltlAbwpYGHFSd1FDL2QVcJVAgppKCuh+U2dfy4tLbqFHW2OlwH7Ocy5EO56/QhnlKhJxYW5ElpoCPHYJBfSCyWZRrXX7OXaWfmQs/Y1ME7G0yZpdmWbhbIT1xTZ0PUB6grt3bRSIwyAyjIPQttNiGed7lWR94vHIjbjZaev4cZFyQC88LeqmuLUOxCmcQNwfxDdhVsXpujov+4+ZSsDnZxud9V96cBpod60YdSZP/n1LSepsAatl214bu33lGUNTnfjdEyj+u9+gDeyk44+PJKODXzaYUfe63AnTWXqbupT2yGRIo5SvWvlDSdcpUEPiNaH6ZtnIsOjq+9A+Lh7GFbDv+W5JfpuCftsJhvvn2WEjecNL+NDmRYVuEkF724PgIs=
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: thinkpixel
    type: Opaque
