apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis/redis-stack:latest
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
              cpu: 250m
          envFrom:
            - secretRef:
                name: redis-secret
          command:
            - /bin/sh
            - -c
            - |
              redis-stack-server \
              --appendonly yes \
              --requirepass ${REDIS_PASSWORD} \
              --maxmemory 1800mb
          ports:
            - containerPort: 6379
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - redis
              topologyKey: kubernetes.io/hostname
