---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qdrant-secret
  namespace: thinkpixel
spec:
  encryptedData:
    QDRANT__SERVICE__API_KEY: <encrypted-api-key>
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: vectordb
        app.kubernetes.io/name: qdrant
      name: qdrant-secret
      namespace: thinkpixel
    type: Opaque
