---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: vectordb
data:
  initialize.sh: |
    #!/bin/sh
    SET_INDEX=$${HOSTNAME##*-}
    # echo "Starting initializing for pod $SET_INDEX and snapshots restoration"
    # exec ./entrypoint.sh --uri 'http://qdrant-0.qdrant:6335' --snapshot ...
    echo "Starting initializing for pod $SET_INDEX"
    if [ "$SET_INDEX" = "0" ]; then
      exec ./entrypoint.sh --uri 'http://qdrant-0.qdrant:6335'
    else
      exec ./entrypoint.sh --bootstrap 'http://qdrant-0.qdrant:6335' --uri 'http://qdrant-'"$SET_INDEX"'.qdrant:6335'
    fi
  production.yaml: |
    cluster:
      enabled: true
      p2p:
        port: 6335
      consensus:
        tick_period_ms: 1000
