---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluent-bit-secret
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCTxFbxtcaISRn+QKyedu0h3eTw2/Nh4WJbRJQJU4tHoyMiJ4gE8J+sms8IuSj+ffzvRUTpFvfOA7//ZE1fuYgRUD6SVlOVwl7eaOvvkhfdHOZ+fgqrmqw/T6WE8pmP0n7rE9XfIuNCfaYwA5xxYV0+ud0yKKRlWJ51KatE9ofNaFx+Jz8VpjSadDMARKOuDPMN0ndJTxJtRDB2bgRrm1F11dwMZcr4AzmGibYT9RdsOxJwVuWipNMuHpy16hs9SUQGwbA0lm8WBdZ19Jbyc0QHyukkeL3Y06RBrjHmhmbrenCPwHvolzqcS6Av4F4b/txQOFILQHfpNI6soTGQCHSI//kPd5HzhCLEQW6Mep/TqoBvY5IPxFMvL2uPenyKuuB6R8k3wwxLSHYi3/2ou6CPPk7wmz0g9NVRnTjARaiu4sRIMZyHFF9BVvJta+uSTZ4rx/BXpUB6O8fHzrHWqb8PXOIbLU2PNh9zy95SQkVT/ztTDrNuJmkTtOhXZ60yKW+s0B+3pChJoB/v3RNiF9Lg2OEP+o8lMgAWoKXi4cqdnyCKFrFh+KdJck3KDVt3M6LBp+Mf85Xk4WeIq3EGp7kdZiEZ8pons/fC/yaCVii0JAdFmT1he7DKA5ID3zqG3C4VW8wXXqlz8Ot0vHjZD3VNYaxMKRc3JyYGsXxG1S6iv63+Bxyv1SdBLaykETTED3il+qqkSJti5BxjOFLG7WXxv2ErlA==
    AWS_SECRET_ACCESS_KEY: AgA76YqTB/m7QKKArAEfksSpZbjv0Cc0CkYDefilgDe5XjHbivay1gRDVQe2elM5DKH22RGA9pKU/Suo8zNDkx5Zz6KPQ+Bh/y/sS6Dk2bS5shWJfJuP+PV3KfpDGPGZiX7dOiQh2x0HpMsiVRPsHOyGBWEDa1u0YcjperNhFgWLuZvqbLmgvHKCNwlkEie9n4zicRcHjYPawpVcfJp5nxZifSc8PJiGZzbpa0eMq6FIxE+NQXC+S9YQbWkLr+p5cdOLfBwbnXOeXOgFqsBPWe9jgoy2VnbiCOgrGyQFhGbIjKEznwbjFfDSbxb4AHioQr/IqvJd9IEAr3w/Qsrahbkm/L2RcBj/ENWdLPZloUJ3tqxWlgNoUHCE+4msFaGLP8khnk67cLiNqNk0V7FYrBLqB1Gg5fXhhQdL5lcljttcTHG6W3XlIEg5tdWNQ46MR5BtLl1vD8V1xUcszNFCtkWfgi1hwnAgIK1mmuGoJFfNu4AdHkC6LscF9t56YnjPKIOz14EMfH/sQUZbCuo/RR6ml0fLYkhvvtxSf0LDiKwCRBYy6ArgxDYKEY0kB+z/7flJN5MLHBwcbLs6EkM+ir7+hQPfwHT04iWzbcMoXQ6ucFzah95huVhJ8r+160VfzmJzUhRhjDWkec94Th1bGQ4W2AgL3yB2CAie30ObirKDbvNe8Y9paWPSs9wgWmkYlVNXA5LnHSpU3p1+bKRX9jQyKH7BPrQRQn4TwAzVcUfkD9cPCUQuD/7q
  template:
    metadata:
      creationTimestamp: null
      name: fluent-bit-secret
      namespace: thinkpixel
    type: Opaque
