---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
spec:
  encryptedData:
    REDIS_PASSWORD: <encrypted-redis-password>
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
    type: Opaque
