apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats
spec:
  secretName: nats-tls-secret
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "thinkpixel"
  issuerRef:
    name: nats
    kind: Issuer
  commonName: nats.nats.svc.${CLUSTER_DOMAIN}
  dnsNames:
    - nats.nats.svc.${CLUSTER_DOMAIN}
  usages:
    - server auth
    - client auth
