apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/helmrelease.yaml
  - ../base/helmrepository.yaml
  - ./certificate.yaml
  - ./issuer.yaml
  - ./nats-nkey-sealed-secret.yaml
configMapGenerator:
  - name: nats
    namespace: nats
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
