---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nats-nkey-secret
  namespace: nats
spec:
  encryptedData:
    nats.nk: AgDJQu++dQdNwYHoN16CCldwPMzMK6ugkUk5Dd0HESEWwq71CQlnO6qI7aRjSgub3Mvs1+MKNOXs/iJoBrIGF9GY+tcpKBsJtQD4gReQcvXs+JF3iIoI6cjZYuGQ7zDyypmokce80a4vMlG2Qz/B5paX2lAnR1WErLsMNJ7VExWS4nF+31vam2aXZ1WvE3wpqOCDOl2vxsG4Yx2O21lH+QYO0Rg+EP8qo1oLtX4USO+D/DqCrzUX/+S9pGTlW8YIzr2XLxpqZInVEhNxrp1ougPZacwvP0u3HxabakRdIV2bGi00yRQCHWmBJcA9DveFOOeMivuUEazJtGwCpohMyLkJKXJORZmd0WHWyxttnZ3FkTkxSP+Yu7ky2ZjAzogjdsm5Cr1TlA+ZlehDSDA8gMMEMmDaDoxul4ZrcV1s89nafy6cVvmTZVE/+kH2PUyKmEbEIzFzmPNO4Bc9mUrmxBoDEVvvVveLgJnPIafFomSmnk59HqgsUZrytgJNvb5HEhigm/+pcIUohtumDcHQk5jX8cUp3Ax13C32xaIjxh4v2ocl+yxfwYTm3Iwbh/ZOVo531W1cENDlmv2/GFc6WRjVBmPhiV0aW7pWAeMcDTWbnYS1nSqWgA6RiozgOT1IRas4fZbagx6R8WjeIQmKZHIz9hLLJ8DHP8uRF32wYr5HOrH+kHCMtiYk4ms/3RJN0e0zYKDD8fCot1oCRhvTMhrGKcPuW1jlGxad5nBdHvRL/98x3Co2tvgFpio0bPdfsubZm3qG0643cs0n
    nats.pub: AgAZpXjR2nJEf8kBIiMOB46i7YN89Pds3yJ+ZY0hyilQuMZWjfAp4k4DPESVm5hrVBtdxG3G9rVZgw+NpsrjbN6/mysNl4rrJNXr5astg+LoD3MD3ZLERdVA9sCe+1w2z1Rdk2eE65hwi2mTABYEle3wG98SgRuGRQ5GRzbCA7GmjgJkJ+UDdMtCbZ4lVMOxKDHgL9totz77bt948qfMzG9L9RArE9YhsJAjRlHkfW+o/b465eqJNsX9ggKlSbilvX174p5mqWXeIBodxaXtDFhCjeHdVyQIxDiam/fZ6XSyw2QSK4i4r/pv6pug7gF+iMQoYsuEjxrX/oLTNJkbhdfVO6I4d+V8MFMyAn3hPYF/wp9KnY5At+tlsouxg5hfUS75F7r5qTakY4mOMRA7qV3O0zBytuxo2tigNhoobr7JQ5iT3/6lVGjd89mOIcCdqcrzgxwOv+11e7K6BU6FjfVjT2p9vImUR5ClXdtMxW2qYkGARObVfJxjKel/Hy215dnz2YVHjk6UderomK/YHScPJPp87UL9knZJcgOtpWHu4XODGv1CNhra8QgQo9fZckQrJ8Qdw9yXKghcs7H5uI7mjX2kTsCpvAvnXS4mo04WqbE2bpGexttdMaFrX2tZg33H8RIZpTUfvIzx2GJM6GjOtBWeWzIuX3SI8A6a63Vm0gMTtgiaHzDDH24FMDmtSXovsGgGTWu1SHUhDnmD8Q55ew0kI7zUfVTayKaez0MJM+ytQMm7MLD9bA23yxQbV3n3EpeOLJHi9A==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: thinkpixel
      creationTimestamp: null
      name: nats-nkey-secret
      namespace: nats
    type: Opaque
