---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nats-nkey-secret
  namespace: nats
spec:
  encryptedData:
    nats.nk: AgAyQQMiljhjzTYAe00zX1ehEOLyM9Gif11n/VQS7h75zSCrkTTQkEEJMTMiBdWu7V9zJyMgV0ZodqOesmNbfyYrMg5A3r4TRPBkPN9/MSELyII0yYKWluDDizgtkB2D6TeWNHdm4fEh3H3x4/Z9nd0QaJJrQtFRawnJ/YDSbb+cQlXvKfFDjPXR332Ynxe7rRYDnqkYTPKI9/us8FLfm/6MCFyrYcd7yetD711eBEEfTX+AEFV96GCpaIO5qkb22AbBgvY23sjjNgRGuOw/lV8CmfpdpEai504UvMllxLPjEihhXS/bC8r48RZ2+yZWIU1kn4tBLQ3bHkjqkxuJsmFQ5P5yBeU7VFHbvz/i/JRMj35Ggu98d283nhAmIRk0K+/BPn/FQXjvgA0czxWOL/KdvCoz0zd/+5HZejXNmn4mvglVkp9Xb0lQJiXk7hAVzSo3PbdF9XxDLoF8OKYGUvaE8czm45j7XH/b4sBrUBWjU4IXc/+LDMuvOXM+FpPBTaAiILrgHFoDftw3FVcSVgAvU+SJGgTD+eLoxG8G2tRUyxHSgRBEPig9p5yL6pxgSf7pMjXZTjifqFkOFH45/eboogbES8eh2lBoK94pw0SMIBuFp8lAAs5MoBDHwAJk+r0MZLCXDHnfleMZvRrGystp69sfwwCOm7ysmnTFkD+K2Cdws9MWfqnxlR/XGkqtsVJWKfnXkWzRCG6JrMgwinNltd+MhAQeMy6wglbtIXK4dVugACs9yieSPA/e8nu94wx7Ywnq5rTfdWUv
    nats.pub: AgAfG2JpKe8lgd6ChEwNRu0857+aprMJzGXNChb+mu14L4njmyzmoD2dfa+SyR3ofiC0NWVOdmWpVREAAon/H207XLDgQwnLM12W1yce8X14B61kKTknsvXAwFbGvMI+xwlDXrsa0lzzT6fz5Yb3Ob1pv9Qw2CzRyot92DQXGDYuazioErWi0mfTS4yqVUXFPH9a8JYkJsqFzCqqPFuZmwaYkGeYolGhiFAKs4ZGB6ZU9RRBUFooanY2IMpnkfNPBUM7WBvPI0Fj5s/usHd3UKIuOa6G31aQPoszR6YP3ZLs5SD7JMHEmKdOpYiLmr1G7vJTbVQwKIzPP1vQCTif1LHxVw8MxMYORn9h96P1pSsw/eRdVCBhfs6t1oBR4keA8pnSaEoVQurBjXgHa/IFzxZLpBO5j4YnYbX+ev0VG1C9SANtpIVxGt3d4jqPd0+3knPaWJhFuaMyPRqSV/YmbvXDamWco7cj5cn2oG5S+rQa2CAPCZMzukRy60oDoSHRa5gITN8giGptQuiaKAzY8KjnUatf4k9PdZ9b9CfQdMY3kusHoG3q+jp/KCBfHV/eAogTqhQYEVQO/PoxDq0CpvuB1KUvu/oeOPGiLjN56sGOGW3HgeE486Z+F2Z0Iil1Wq5VF/wmRTMNM6ME7T5gfU9QMkB0l8S/2TQN/M9YN10J0SpSElPwmeu6zNLKXEuiOLEfaMieTCd1hueGuhV4wO66IIOM4GLzEr9PpSLYfU60MdFzNwnZC/Dk5mIsNLlsCgPfubTKsEFKeQ==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: thinkpixel
      creationTimestamp: null
      name: nats-nkey-secret
      namespace: nats
    type: Opaque
