---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nats-nkey-secret
spec:
  encryptedData:
    nats.nk: AgAeVQO8Jt3Y0mknRDsbh0eRLP9QB7TUZL2ZqaFX5Pxwy1w/1FP8aWr0nObhEonY7dBdSK5v1RvJEQtLt0XcvSd+k6M9TJPUkqfEuD+K+vbIWJODqvKBL4H2WrdEC3hZ/iRYWBQ3mg11QNGi9ZIvwZqsNEQTY9TB2OyVS8DZCgQUClp3AhVzXM7+u5OCTKyAchex+szq1S2PpEF5ViFTYj+XxgEykR7VlpsDkGmAPIvboqBGBhBCDEnpPZkN2fR+lUIclhixF/0evXKGVlH8nUClTW7dOOm/4NinuMpy5rXQ/EuYHnIB+fFC9A7OvAqOX1+TGm1L8zEI9k9MVcMrsgTar6ogAxqQG+wz//BnGZy6A+SWVvXnSHG9HZqAcsBUKYQ5lZWoq3LdeYc0NMo0jwN+utnVlspZNAM/ASIZcOIoFgwc/teQ7Fe8LBGUR9a2/lO1l4J5XTteRSCNbOZRSctDVdtrMD40vcwAZaOypk/tBynZ53EPUhBXjTbE9YWB1l6jrUILjXtd+r3IJCDtowFNBHpZXWzuNsc+ZGuO+jE2fGKGSpI/Id0bqV1nSUixHdL1mk6A4E20BlMgC6KJCASBsticMRHAtAFZGxe0ORknE4iiIHfZpz3Ygmnw02+uTXCTZrwKsZ74hzeQWEw3Or/glHBIA02B/82KHC5pxyUZcEMrvhHShF2TBIdVcJlBJgPyt5m5aQCeLjsyGU2r2CPv2kA6R0Wo3ZiWOXr5FsMYyGCFh959dxLQBmrgaanlY/09COUiBQoWsStW
    nats.pub: AgCHEMP3nkneDsjMINbBTCttE2I1IqrenAt4ntInBpOR1DkZwAf2KGGVNbrFmuAk/w66s9SInsBBlpSoRF6ZWdTA7FgP8ruW8c1CGP0xGZwp+BuTlGhJNIC98nzcBFlYDX2DcMO3Bn01GifiNA8ctbQfRJrvD1MCtlyujCwJ7c0mM5olDryiJ196poRFr3gkRualxdheJ99RBXU7UUKTbX09XmKndxnpM6Nb+ZDu24XtPwkBxJwID/0m9hbBNkrjtsfnsdSkVW7FFQo8HU+fS7KkeizD1T5FeOy0HGQjR+N2ntxBRx5szyHD9KZcB82a22ax0craALyIYrIAyabkD/bmP+K/P9rarvlCLnOh4LY5P4R3Lcwczow5OWmtF3rSYdPI0wNx9LMdxQUZg7dFhGJNw38QRVcfsQ/k2yFZNoUKpfJCh1ctDXn8MtUzU1vPgzvJIK3/TGJQq5AAhof5uHbz2/kOiFKJSdDhgRA6ck5YuHV4Dw7Lp0nZwLlTJm/kH7ugBsHoTKQ5xBltqbnm2iIb/80IB2ztwLeIjdKbRtIS3t+alHNU50DLlRlJS/MaS8BDJfNpUOYAPU4S0Qu1mhxPaNIURlzESv7jOtLXabVorfbVMyXLb81U48KnlpbS/vd3lJB5OP6uzBMtR2IvLqOI+eQh4X1od0V6R3hMvTlrVx/cYNWpJIyVAgXeiGGKbdkhpTeYKGXBaQhVpkpivwUMVGvtcHD+L5DFoiFp/iqpzUIKMst0uqcChoIqevb0VfkHwvbFYV4vtQ==
  template:
    metadata:
      creationTimestamp: null
      name: nats-nkey-secret
    type: Opaque
