# Core only
tlsCA:
  enabled: true
  secretName: nats-tls-secret
config:
  jetstream:
    enabled: false
  cluster:
    enabled: false
  nats:
    tls:
      enabled: true
      secretName: nats-tls-secret
  merge:
    authorization:
      users:
        - nkey: UDFMYYFHYUWB45ZERYKFE4PBXSJZ4UAYQ7YBI3L64F6K4MCLUEJHKKEZ
natsBox:
  enabled: true
  contexts:
    default:
      nkey:
        secretName: nats-nkey-secret
      tls:
        enabled: true
        secretName: nats-tls-secret
      merge:
        url: nats://nats.nats.svc.${CLUSTER_DOMAIN}:4222
promExporter:
  enabled: true
podTemplate:
  merge:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
        prometheus.io/path: "/metrics"
