apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/version: 0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: quay.io/bdobrica/thinkpixel-api-gateway-multi:0.1.12
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: redis-secret
            - secretRef:
                name: mysql-secret
            - secretRef:
                name: api-gateway-secret
          env:
            - name: API_GATEWAY_DB_DSN
              value: "$(API_GATEWAY_MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(API_GATEWAY_MYSQL_HOST):$(API_GATEWAY_MYSQL_PORT))/$(API_GATEWAY_MYSQL_DB)"
            - name: API_GATEWAY_REDIS_PASSWORD
              value: "$(REDIS_PASSWORD)"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      imagePullSecrets:
        - name: quay-io-credentials

