---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
spec:
  encryptedData:
    API_GATEWAY_JWT_SECRET: <encrypted-jwt-secret>
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluent-bit-secret
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: <encrypted-access-key-id>
    AWS_SECRET_ACCESS_KEY: <encrypted-secret-access-key>
  template:
    metadata:
      creationTimestamp: null
      name: fluent-bit-secret
    type: Opaque
