// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: document_queue.proto

package document_queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentQueuePayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SiteId          int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Id              int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Text            string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampMillis int64                  `protobuf:"varint,5,opt,name=timestampMillis,proto3" json:"timestampMillis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentQueuePayload) Reset() {
	*x = DocumentQueuePayload{}
	mi := &file_document_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentQueuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentQueuePayload) ProtoMessage() {}

func (x *DocumentQueuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_document_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentQueuePayload.ProtoReflect.Descriptor instead.
func (*DocumentQueuePayload) Descriptor() ([]byte, []int) {
	return file_document_queue_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentQueuePayload) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *DocumentQueuePayload) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocumentQueuePayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DocumentQueuePayload) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *DocumentQueuePayload) GetTimestampMillis() int64 {
	if x != nil {
		return x.TimestampMillis
	}
	return 0
}

var File_document_queue_proto protoreflect.FileDescriptor

const file_document_queue_proto_rawDesc = "" +
	"\n" +
	"\x14document_queue.proto\x12\rdocumentqueue\"\xfd\x01\n" +
	"\x14DocumentQueuePayload\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12D\n" +
	"\x05extra\x18\x04 \x03(\v2..documentqueue.DocumentQueuePayload.ExtraEntryR\x05extra\x12(\n" +
	"\x0ftimestampMillis\x18\x05 \x01(\x03R\x0ftimestampMillis\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x1cZ\x1aapi_gateway/document_queueb\x06proto3"

var (
	file_document_queue_proto_rawDescOnce sync.Once
	file_document_queue_proto_rawDescData []byte
)

func file_document_queue_proto_rawDescGZIP() []byte {
	file_document_queue_proto_rawDescOnce.Do(func() {
		file_document_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_queue_proto_rawDesc), len(file_document_queue_proto_rawDesc)))
	})
	return file_document_queue_proto_rawDescData
}

var file_document_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_document_queue_proto_goTypes = []any{
	(*DocumentQueuePayload)(nil), // 0: documentqueue.DocumentQueuePayload
	nil,                          // 1: documentqueue.DocumentQueuePayload.ExtraEntry
}
var file_document_queue_proto_depIdxs = []int32{
	1, // 0: documentqueue.DocumentQueuePayload.extra:type_name -> documentqueue.DocumentQueuePayload.ExtraEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_document_queue_proto_init() }
func file_document_queue_proto_init() {
	if File_document_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_queue_proto_rawDesc), len(file_document_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_document_queue_proto_goTypes,
		DependencyIndexes: file_document_queue_proto_depIdxs,
		MessageInfos:      file_document_queue_proto_msgTypes,
	}.Build()
	File_document_queue_proto = out.File
	file_document_queue_proto_goTypes = nil
	file_document_queue_proto_depIdxs = nil
}
