apiVersion: v1
kind: Secret
metadata:
  name: scylla-secrets
type: Opaque
data:
  # Base64 of the entire scylla.p12 file
  scylla-p12: "BASE64_OF_SCYLLA_P12_HERE"
  
  # Base64 of the keystore password (changeit in our example)
  scylla-p12-password: "Y2hhbmdlIG1lIQ==" 

  # Example user and password for Scylla PasswordAuthenticator
  db-username: "bXl1c2Vy"
  db-password: "bXlzZWNyZXRwYXNz"
