name: Deploy to Dev Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/overlay/dev/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DEV }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -k k8s/overlay/dev/
